apiVersion: v2
name: kubernetes-demo
description: A Helm chart for kubernetes-demo Spring Boot application
type: application
version: 1.0.0
appVersion: "0.0.1-SNAPSHOT"
keywords:
  - spring-boot
  - java
  - kubernetes
maintainers:
  - name: SangkiHan
